projects:
  appdatastoreblog:
    schemaPath: app-datastore-blog/src/main/graphql/schema.json
    includes:
      - app-datastore-blog/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: >-
          app-datastore-blog/src/main/graphql/com/amazonaws/amplify/generated/graphql
extensions:
  amplify:
    version: 3
